name: Deploy MultiDocker

on:
  push:
    branches:
      - master # Change this to 'main' if that's your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Log in to DockerHub
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build and test the client with Dockerfile.dev
      - name: Build and Test Client
        run: |
          docker build -t rallycoding/react-test -f ./client/Dockerfile ./client
          docker run -e CI=true rallycoding/react-test npm test

      # Build Docker images for all services
      - name: Build Docker Images
        run: |
          docker build -t rallycoding/multi-client ./client
          docker build -t rallycoding/multi-nginx ./nginx
          docker build -t rallycoding/multi-server ./server
          docker build -t rallycoding/multi-worker ./worker

      # Push Docker images to DockerHub
      - name: Push Docker Images
        run: |
          docker push rallycoding/multi-client
          docker push rallycoding/multi-nginx
          docker push rallycoding/multi-server
          docker push rallycoding/multi-worker
